// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

/**
왜 존재하는가?
 - C++와 에디터 에셋이 공유하는 GameplayTag를 네이티브로 선언한다(문자열 오타 방지).
무엇을 저장하는가?
 - 프로젝트 전역 태그 심볼. 현재는 데미지 SetByCaller 태그.
멀티플레이 역할?
 - 모든 머신에 동일 등록. 복제 불필요.
 */
namespace OBGameplayTags
{
	// 데미지 GE에 수치를 실어 보내기 위한 SetByCaller 키.
	// GE_Damage의 Modifier Magnitude(Set By Caller)와 동일한 태그여야 한다.
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Damage);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(SetByCaller_Heal);
	
	// 입력
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Fire);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Reload);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Aim);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Consumable_Heal);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Consumable_Grenade);
	
	// 상태
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Downed);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Reloading);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Aiming);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Weapon_Switching);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_UsingConsumable);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Melee_Attacking);
	
	// 연출(발사 - 총구 화염/사격음, 피격 - 탄착 이펙트/사운드 등).
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Fire);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Weapon_Impact);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Melee_Swing);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Melee_Impact);
	
	// 탄약 타입(인벤토리 탄약 풀의 키). 무기마다 자기 타입을 지정.
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_AssaultRifle);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_SniperRifle);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_SMG);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_Shotgun);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_Pistol);
	
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Melee);

	// Data-driven stat identifiers used by attachment modifiers and tooltip rows.
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_Damage);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_Range);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_Mobility);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_HeadshotMultiplier);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_MagazineSize);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_RoundsPerMinute);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_RecoilVertical);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_RecoilHorizontal);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_RecoilRecovery);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_ADSFOV);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_ADSSpeed);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_ADSRecoil);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_SpreadBase);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_SpreadADS);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Weapon_SpreadMoving);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Melee_Reach);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Melee_SweepRadius);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Melee_Arc);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Melee_HitTime);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Melee_AttackDuration);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Melee_StaminaCost);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Player_MaxHealth);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Player_MaxStamina);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Player_MoveSpeed);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Player_CarryCapacity);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Player_RecoilControl);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Player_AimStability);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Player_MeleePower);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Stat_Player_Armor);
	
	// 아이템
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Bandage);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Grenade);
	
	// 아이템 - 무기. 창고/가방은 이 태그로 무기를 지목하고, 실제 BP는 ItemDefinition.WeaponClass가 가리킨다.
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_AssaultRifle);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_SniperRifle);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Shotgun);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_Pistol);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Weapon_FireAxe);
	
	// 아이템 - 귀중품. 쓸 데 없고 팔기만 하는 루팅 주 수입원. 아래 2개는 자리만 잡은 예시.
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Valuable_Watch);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Valuable_Gold);
	
	// 아이템 - 재료. 제작이 붙기 전까지는 귀중품과 동일하게 판매용.
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_Scrap);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Material_Cloth);

	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttachmentSlot_Optic);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttachmentSlot_Muzzle);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttachmentSlot_Magazine);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttachmentSlot_Stock);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttachmentSlot_Grip);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(AttachmentSlot_Melee_Mod);
	
	
	// AI State Tree
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_StateTree_Event_TargetSighted);
	OUTBREAK_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_StateTree_Event_MemoryUpdated);
	
}
